import { NextResponse } from "next/server";
import { explainDisruption, factsFrom } from "@/lib/explain";
import { delayFrom, resolveScenario } from "@/lib/scenario";
import type { Journey } from "@/lib/types";

export const dynamic = "force-dynamic";

/**
 * POST /api/ai/disruption-note
 *
 * Turns two already-planned journeys into one plain-language sentence in
 * English and Hindi. The client sends the journeys it is displaying, so the
 * copy can never describe a route the rider is not looking at.
 *
 * The model phrases; it does not decide. Every number is re-checked against
 * the router's own figures before the sentence is returned.
 */
export async function POST(request: Request) {
  let body: { disrupted?: Journey; alternative?: Journey; scenario?: unknown };
  try {
    body = (await request.json()) as typeof body;
  } catch {
    body = {};
  }

  const { disrupted, alternative } = body;
  if (!isJourney(disrupted) || !isJourney(alternative)) {
    return NextResponse.json(
      {
        error: "BAD_JOURNEYS",
        message: "Send the disrupted and alternative journeys.",
      },
      { status: 400 },
    );
  }

  const scenario = resolveScenario(body.scenario);
  const delay = delayFrom(scenario);
  if (!delay) {
    return NextResponse.json(
      { error: "NO_DISRUPTION", message: "No active disruption to explain." },
      { status: 400 },
    );
  }

  const facts = factsFrom(
    disrupted,
    alternative,
    delay.routeNumber,
    delay.minutes,
  );
  const note = await explainDisruption(facts);

  return NextResponse.json(
    {
      ...note,
      facts,
      // Must match what actually happened: claiming AI wrote template copy
      // would be exactly the kind of dishonesty this feature exists to avoid.
      disclosure:
        note.source === "openai"
          ? `Wording generated by ${note.model} from the planner's own numbers. Times, fares and routes come from the deterministic planner.`
          : "Wording from a built-in template. Times, fares and routes come from the deterministic planner.",
    },
    { headers: { "Cache-Control": "no-store" } },
  );
}

/** Shallow shape check - we only read a handful of fields. */
function isJourney(j: unknown): j is Journey {
  if (typeof j !== "object" || j === null) return false;
  const c = j as Partial<Journey>;
  return (
    typeof c.durationMinutes === "number" &&
    Number.isFinite(c.durationMinutes) &&
    typeof c.fareInr === "number" &&
    Array.isArray(c.legs)
  );
}
